### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by nayyaung9** [cryptostrike-mm/cryptostrike-mm.github.io#1]
by open sourcing is great. But be aware of malicious codes review from anonymous. 
I was a developer who built revolutional webs and apps before. Especially genzmap. 
I got an idea for further more projects will be going in open source by anonymously.

Thank you for your creation!

**Comment by cryptostrike-mm** [comment]
Thanks for reaching out. Yes, I will never accept any external commits to
my code. Thank you for your concern. And stay safe my brother!
